[global]
server_name = "localhost:6167"
database_backend = "rocksdb"
database_path = "/var/lib/matrix-conduit/"
port = 6167
address = "0.0.0.0"
allow_registration = true
allow_federation = false
max_request_size = 20_000_000
trusted_servers = []
